services:
  - type: web
    name: swefire-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_SSL
        value: "true"
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: swefire-backend
          property: host
